name: Destroy-Infra-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables:
  TF_VAR_region: "us-east-1"
  TF_VAR_s3_bucket: "terraform-backend-prueba"
  TF_VAR_s3_key: "iac/terraform.tfstate"
  TF_VAR_s3_dynamodb_table: "terraform-lock"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Terraform_Destroy
    displayName: "💣 Destrucción de Infraestructura en AWS"
    jobs:
      - job: DestroyJob
        displayName: "Terraform Destroy"
        steps:
          - task: TerraformInstaller@1
            displayName: "🧰 Instalar Terraform"
            inputs:
              terraformVersion: "latest"

          - task: TerraformTaskV4@4
            name: TerraformInit
            displayName: "🌱 Inicializar Terraform (backend)"
            inputs:
              provider: "aws"
              command: "init"
              backendServiceAWS: "aws-terraform-prueba-eks"
              backendAWSBucketName: "$(TF_VAR_s3_bucket)"
              backendAWSKey: "$(TF_VAR_s3_key)"
              backendAWSRegion: "$(TF_VAR_region)"
              backendAWSDynamoDBTable: "$(TF_VAR_s3_dynamodb_table)"
              workingDirectory: "$(System.DefaultWorkingDirectory)/iac"

          - task: TerraformTaskV4@4
            name: TerraformDestroy
            displayName: "💥 Ejecutar Terraform Destroy"
            inputs:
              provider: "aws"
              command: "destroy"
              workingDirectory: "$(System.DefaultWorkingDirectory)/iac"
              environmentServiceNameAWS: "aws-terraform-prueba-eks"
